
import { Metadata } from "next";
import "./globals.css";
import "./App.css";
import Header from "@/components/Header";
import { Inter, Montserrat } from "next/font/google";
import GlobalStyle from "../components/globalStyle";
const montserrat = Montserrat({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GlobalStyle />
      <body className={inter.className}>
        <Header />
        <div style={{ paddingTop: "133px" }}>{children}</div>
      </body>
    </html>
  );
}
