"use client"
import './globals.css'
import { Inter, Montserrat } from 'next/font/google'
import './App.css'
import Header from '@/components/Header'
const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <style jsx global>
        {
        `
        h1 {
          font-family: ${montserrat.style.fontFamily};
        }
        h2 {
          font-family: ${montserrat.style.fontFamily};
        }
        h3 {
          font-family: ${montserrat.style.fontFamily};
        }
        h4 {
          font-family: ${montserrat.style.fontFamily};
        }
        .montserrat {
          font-family: ${montserrat.style.fontFamily}
        }
        `
        }
      </style>
      <body className={inter.className}>
        <Header />
        <div style={{paddingTop: '133px'}}>
        {children}
        </div>
        </body>
    </html>
  )
}
